# Generated by Django 3.2.5 on 2021-07-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210726_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
